client/kiri/package-lock.json, client/kiri/package.json, client/kiri/src/App.js, client/kiri/src/pages/MainPage.js, client/kiri/src/pages/NoMatchPage.js, client/kiri/src/styles/Globalstyle.js, client/kiri/src/styles/theme.js
=> [FE] 기본 설정 적용

client/.eslintrc.json, client/kiri/src/components/Header.js
=> 🐛 [FE] fix : prettier 오류 수정

client/kiri/src/pages/Main/MainCarousel.js, client/kiri/src/pages/Main/MainEvents.js, client/kiri/src/pages/Main/MainPage.js, client/kiri/src/pages/Main/SelectedEvents.js
=> [FE] 메인페이지 이벤트 목록 UI 구현

client/kiri/src/Components/Footer.js, client/kiri/src/components/Header.js, client/kiri/src/containers/PageContainer.js, client/kiri/src/pages/Main/BestEvents.js, client/kiri/src/pages/Main/MainCarousel.js, client/kiri/src/pages/Main/MainEvents.js, client/kiri/src/pages/Main/MainPage.js, client/kiri/src/pages/Main/SelectedEvents.js
- 헤더, 푸터 화면 크기 넘치는 레이아웃 조금 수정
- 메인페이지 UI 1차적으로는 완성
- 수정할거 있으면 알려주삼!
=> [FE] 메인페이지 UI 대략적으로 구현 완료

client/kiri/src/App.js, client/kiri/src/components/Header.js, client/kiri/src/pages/Signup/SignupInputs.js, client/kiri/src/pages/Signup/SignupPage.js
- 회원가입 페이지 UI
- 이메일 등 간단한 유효성 검사
- 입력 받을 필드, 유효성 조건 등 회의 때 정해야함!
=> [FE] 회원가입 페이지 1차 구현

client/kiri/src/App.js, client/kiri/src/components/Header.js, client/kiri/src/pages/Main/MainCarousel.js, client/kiri/src/pages/Signin/SigninInputs.js, client/kiri/src/pages/Signin/SigninPage.js, client/kiri/src/pages/Signup/SignupInputs.js
- 로그인 페이지 구현
- 헤더에서 로그인 버튼 클릭시 로그인 페이지 -> 회원가입하러가기 버튼으로 회원가입 페이지로!
=> [FE] 로그인 페이지

client/kiri/.gitignore, client/kiri/package-lock.json, client/kiri/package.json, client/kiri/src/App.js, client/kiri/src/api/axios.js, client/kiri/src/setupProxy.js
- .env 파일 생성
- http-proxy-middleware로 Proxy 사용
- api 객체 생성
=> [FE] CORS, axios 관련 설정들

client/kiri/src/pages/Signup/SignupInputs.js, client/kiri/src/setupProxy.js, client/kiri/src/styles/theme.js
- setupProxy 때문에 에러나는거 수정
- 회원가입 이메일 중복시 메시지 추가
=> [FE] proxy 에러 수정, 회원가입 UI 수정

client/kiri/src/App.js, client/kiri/src/components/Header.js, client/kiri/src/containers/PageContainer.js, client/kiri/src/pages/Mypage/Mypage.js, client/kiri/src/pages/Mypage/MypageInput.js, client/kiri/src/pages/Mypage/MypageInputs.js, client/kiri/src/pages/Mypage/Withdraw.js, client/kiri/src/pages/Signin/SigninPage.js, client/kiri/src/pages/Signup/SignupInputs.js, client/kiri/src/pages/Signup/SignupPage.js
- PageContainer에서 하단 회색 부분 margin 유무 설정가능
- 마이페이지 구현
갈길이 멀다..
=> [FE] 마이페이지

client/kiri/src/pages/Mypage/Mypage.js, client/kiri/src/pages/Mypage/MypageInput.js, client/kiri/src/pages/Signin/SigninInputs.js, client/kiri/src/pages/Signin/SigninPage.js, client/kiri/src/pages/Signup/SignupInputs.js, client/kiri/src/pages/Signup/SignupPage.js
- 마이페이지에 유효성 검사 추가
- 비밀번호 입력시 보기 버튼 추가
=> [FE] 마이페이지, 로그인, 회원가입 페이지 추가 기능

client/kiri/src/App.js, client/kiri/src/pages/Event/EventInfoPage.js
=> Feat/event info page 완성

client/kiri/src/components/Header.js
=> Feat/header [FE] style: 검색창 디자인 수정

client/kiri/src/pages/Mypage/MypageInput.js, client/kiri/src/pages/Mypage/MypageInputs.js, client/kiri/src/pages/Signin/SigninInputs.js, client/kiri/src/pages/Signup/SignupInputs.js
- 회원가입, 로그인에 닉네임, 비밀번호 유효성 검사 조건 추가
- 관심분야에 기타 필드 추가(선택안함 필드 제거)
=> [FE] 회원가입, 로그인, 마이페이지 유효성 검사 및 필드 수정

client/kiri/src/pages/Mypage/MypageInput.js, client/kiri/src/pages/Signup/SignupInputs.js
- 회원가입 페이지, 마이페이지에 비밀번호 조건 안내문구 추가 (영문,숫자 8-16글자)
=> [FE] 회원가입 페이지, 마이페이지 비밀번호 조건 안내문구 추가

client/kiri/src/Components/WithdrawlModal.js, client/kiri/src/pages/Mypage/Withdraw.js
=> [FE] 마이페이지 탈퇴하기 모달

server/kiri/src/main/java/com/ssu/kiri/config/WebMvcConfig.java
WebMvcConfig 파일 추가
이후 옵션 변경 가능
=> [BE] WebMvcConfig 파일 추가

client/kiri/src/App.js, client/kiri/src/components/Header.js, client/kiri/src/pages/EventWrite/EventEtcInput.js, client/kiri/src/pages/EventWrite/EventExplainInput.js, client/kiri/src/pages/EventWrite/EventInfoInput.js, client/kiri/src/pages/EventWrite/EventTitleInput.js, client/kiri/src/pages/EventWrite/EventWritePage.js
- 이벤트 게시물 작성페이지 작업
- 이미지 업로드는 구현예정!
=> [FE] 이벤트 게시물 작성페이지

client/kiri/src/pages/EventWrite/EventEtcInput.js, client/kiri/src/pages/EventWrite/EventWritePage.js
=> [FE] 이미지 업로드 기능

client/kiri/src/pages/EventWrite/EventWritePage.js
- 글쓰기 부분에서 이미지 포함한 formData 작업
=> [FE] 글쓰기 요청 이미지 포함한 formData 전송

server/kiri/build.gradle, server/kiri/src/main/java/com/ssu/kiri/KiriApplication.java, server/kiri/src/main/java/com/ssu/kiri/member/Member.java, server/kiri/src/main/java/com/ssu/kiri/member/MemberController.java, server/kiri/src/main/java/com/ssu/kiri/member/MemberRepository.java, server/kiri/src/main/java/com/ssu/kiri/member/MemberService.java, server/kiri/src/main/java/com/ssu/kiri/member/dto/MemberReqDto.java, server/kiri/src/main/java/com/ssu/kiri/member/dto/MemberResDto.java, server/kiri/src/main/java/com/ssu/kiri/member/mapper/MemberMapper.java, server/kiri/src/main/java/com/ssu/kiri/security/SecurityConfig.java, server/kiri/src/main/java/com/ssu/kiri/security/auth/PrincipalDetails.java, server/kiri/src/main/java/com/ssu/kiri/security/auth/PrincipalDetailsService.java, server/kiri/src/main/java/com/ssu/kiri/security/handler/MemberLogoutHandler.java, server/kiri/src/main/java/com/ssu/kiri/security/jwt/JwtAuthenticationFilter.java, server/kiri/src/main/java/com/ssu/kiri/security/jwt/JwtAuthorizationFilter.java, server/kiri/src/main/java/com/ssu/kiri/security/jwt/JwtProperties.java, server/kiri/src/main/java/com/ssu/kiri/security/jwt/JwtTokenProvider.java
회원가입, 로그인 구현
로그인 URL 변경 ,
refresh token 사용X
=> 회원가입, 로그인 구현, gradle 변경, Member entity 추가

client/kiri/src/pages/Main/BestEvents.js, client/kiri/src/pages/Main/MainEvents.js, client/kiri/src/pages/Main/SelectedEvents.js
=> [FE] 메인페이지 이벤트 조회 UI 수정

client/kiri/src/components/Header.js
`그룹` 빼고 라인 수정
페이지별로 라인뜨는거는 아직 하는 중
=> [FE] feat: header 선택 라인 디자인 수정

client/kiri/src/App.js, client/kiri/src/pages/Event/EventSearchPage.js
=> [FE] feat: Searh Page 완성

client/kiri/src/Components/Footer.js, client/kiri/src/components/Header.js
- 검색창 outline 효과, 아이콘 색깔 등 디자인 조금 수정!
=> [FE] 헤더, 푸터 디자인 수정

client/kiri/src/App.js
=> [FE] 이벤트 상세 페이지 라우터 수정

client/kiri/src/components/Header.js
=> [FE] 헤더 게시요청 -> 글쓰기로 변경

server/kiri/build.gradle, server/kiri/src/main/java/com/ssu/kiri/member/Member.java, server/kiri/src/main/java/com/ssu/kiri/member/MemberController.java, server/kiri/src/main/java/com/ssu/kiri/member/MemberRepository.java, server/kiri/src/main/java/com/ssu/kiri/member/MemberService.java, server/kiri/src/main/java/com/ssu/kiri/member/dto/MemberReqDto.java, server/kiri/src/main/java/com/ssu/kiri/member/dto/MemberResDto.java, server/kiri/src/main/java/com/ssu/kiri/member/mapper/MemberMapper.java, server/kiri/src/main/resources/application.yml, server/kiri/src/test/java/com/ssu/kiri/infra/WithAccount.java, server/kiri/src/test/java/com/ssu/kiri/infra/WithAccountSecurityContextFactory.java, server/kiri/src/test/java/com/ssu/kiri/member/MemberControllerTest.java, server/kiri/src/test/java/com/ssu/kiri/member/MemberTest.java
mypage 구현
개인정보 수정할때 버튼 한번으로 저장할지, 따로 따로 저장할지
=> [BE] mypage 구현

client/kiri/package-lock.json, client/kiri/package.json, client/kiri/src/App.js, client/kiri/src/index.js, client/kiri/src/pages/reduxPage.js, client/kiri/src/store/modules/counterSlice.js, client/kiri/src/store/store.js
- redux, redux toolkit 초기 세팅 적용
- 예제 추가
- 테스트 페이지 생성
- localhost:3000/redux 로 테스트 페이지 접근 가능
=> [FE] Redux, Redux-toolkit 초기 세팅, 테스트 페이지

client/kiri/src/store/store.js
- redux-persist 에러 해결 방법 수정
참고 https://redux-toolkit.js.org/usage/usage-guide#working-with-non-serializable-data
=> [FE] redux-persist 관련 수정

client/kiri/src/Components/SignupModal.js, client/kiri/src/pages/Signup/SignupInputs.js, client/kiri/src/store/modules/authSlice.js, client/kiri/src/store/modules/userSlice.js, client/kiri/src/store/store.js
- redux에 token 저장하는 slice 추가
- 회원가입 api 연결
- 회원가입 UI 수정
=> [FE] 회원가입 관련 처리

client/kiri/src/pages/Signin/SigninInputs.js
=> [FE] 로그인 api 연결

client/kiri/src/Components/SignupinModal.js, client/kiri/src/components/Header.js, client/kiri/src/pages/Signin/SigninInputs.js, client/kiri/src/pages/Signup/SignupInputs.js, client/kiri/src/store/modules/userSlice.js
=> [FE] 로그인 관련 처리

server/kiri/src/main/java/com/ssu/kiri/member/MemberController.java, server/kiri/src/main/java/com/ssu/kiri/member/MemberRepository.java, server/kiri/src/main/java/com/ssu/kiri/member/MemberService.java, server/kiri/src/main/java/com/ssu/kiri/member/dto/request/LoginReqDto.java, server/kiri/src/main/java/com/ssu/kiri/member/dto/request/PostMemberReqDto.java, server/kiri/src/main/java/com/ssu/kiri/member/dto/response/LoginResDto.java, server/kiri/src/main/java/com/ssu/kiri/member/dto/response/PostMemberResDto.java, server/kiri/src/main/java/com/ssu/kiri/security/jwt/JwtAuthenticationFilter.java, server/kiri/src/test/java/com/ssu/kiri/member/MemberControllerTest.java, server/kiri/src/test/java/com/ssu/kiri/member/MemberTest.java
회원가입 response dto 수정
로그인 response dto 추가
이메일 중복 체크 api 추가
로그인 완료 response dto에 password가 필요할까?
=> 회원가입, 로그인 관련 수정

client/kiri/src/components/Header.js
- 로그인 / 로그아웃 버튼 변경
- 미로그인 상태에서 마이페이지 버튼 클릭시 로그인 페이지로 이동
=> [FE] 로그인 여부에 따라 헤더 링크주소 변경

client/kiri/src/components/Header.js, client/kiri/src/pages/Signup/SignupInputs.js
- 회원가입시 이메일 중복검사 api 연결
- 마이페이지 버튼: 로그인 상태에서 마이페이지로 이동 / 미로그인시 로그인페이지로 이동
=> [FE] 회원가입, 로그인 관련 수정

client/kiri/src/pages/Signup/SignupInputs.js
=> [FE] 이메일 중복검사 확인 코드 수정

server/kiri/src/main/java/com/ssu/kiri/post/Post.java, server/kiri/src/main/java/com/ssu/kiri/post/PostRepositoryCustom.java, server/kiri/src/main/java/com/ssu/kiri/post/PostRepositoryImpl.java, server/kiri/src/main/java/com/ssu/kiri/post/PostService.java, server/kiri/src/main/java/com/ssu/kiri/scrap/Scrap.java, server/kiri/src/main/java/com/ssu/kiri/scrap/ScrapController.java, server/kiri/src/main/java/com/ssu/kiri/scrap/ScrapRepository.java, server/kiri/src/main/java/com/ssu/kiri/scrap/ScrapService.java, server/kiri/src/main/java/com/ssu/kiri/scrap/dto/ScrapReqAdd.java, server/kiri/src/test/java/com/ssu/kiri/config/TestConfig.java, server/kiri/src/test/java/com/ssu/kiri/member/MemberControllerTest.java, server/kiri/src/test/java/com/ssu/kiri/member/MemberTest.java, server/kiri/src/test/java/com/ssu/kiri/post/PostControllerTest.java, server/kiri/src/test/java/com/ssu/kiri/post/PostServiceTest.java, server/kiri/src/test/java/com/ssu/kiri/scrap/ScrapControllerTest.java, server/kiri/src/test/java/com/ssu/kiri/scrap/ScrapServiceTest.java
글 조회시 좋아요 개수 누락 추가
좋아요 기능 추가
좋아요 취소 기능 추가
테스트 코드 실행 시 에러 발생으로 모든 테스트 코드에 TestConfig 파일 import.
=> 좋아요(스크랩) 기능 추가

client/kiri/src/App.js, client/kiri/src/pages/Event/EventContent.js, client/kiri/src/pages/Event/EventPage.js, client/kiri/src/pages/Event/EventRegion.js, client/kiri/src/pages/Event/EventTag.js
- 이벤트 변경사항 `학교 page` 작업
- `지역 page` 작업
기존 피그마 디자인에서 X 버튼 생기는거 말고 누른것만 색깔 변하도록 구현!
content 기준 안맞는건 추후에 수정할 예정..........
=> ✨ [FE] feat: event 페이지 구현

client/kiri/src/components/Header.js, client/kiri/src/components/NeedLoginModal.js, client/kiri/src/pages/Mypage/Mypage.js
- 헤더 마이페이지 버튼 로그인 여부에 따라 링크 연결
- 미로그인시 마이페이지 접근 차단
=> [FE] 마이페이지 관련 작업

server/kiri/src/main/java/com/ssu/kiri/member/Member.java, server/kiri/src/main/java/com/ssu/kiri/member/MemberController.java, server/kiri/src/main/java/com/ssu/kiri/member/MemberService.java, server/kiri/src/main/java/com/ssu/kiri/member/dto/request/CheckPassword.java, server/kiri/src/main/java/com/ssu/kiri/member/dto/request/UpdateDto.java, server/kiri/src/main/java/com/ssu/kiri/post/PostRepositoryCustom.java, server/kiri/src/main/java/com/ssu/kiri/post/dto/request/CheckPassword.java, server/kiri/src/test/java/com/ssu/kiri/member/MemberControllerTest.java, server/kiri/src/test/java/com/ssu/kiri/member/MemberTest.java
mypage 개인정보 수정 api 수정
비밀번호 확인 api 추가
개인정보 수정시 dto 바뀜
=> [BE] mypage api 수정

client/kiri/src/pages/Event/EventPage.js, client/kiri/src/pages/Event/EventRegion.js
- 본인 학교가 뜨는 것에서 전체 학교가 뜨는 것으로 수정
=> [FE] 학교 검색 디자인 수정

client/kiri/src/App.js, client/kiri/src/components/Header.js, client/kiri/src/components/container/Header.js, client/kiri/src/pages/Event/EventContent.js, client/kiri/src/pages/Event/EventInfoPage.js, client/kiri/src/pages/Event/EventRegion.js, client/kiri/src/pages/Mypage/Mypage.js, client/kiri/src/pages/Mypage/MypageInput.js, client/kiri/src/pages/Mypage/MypageInputs.js, client/kiri/src/pages/PasswordChange/PasswordChangePage.js, client/kiri/src/store/modules/authSlice.js, client/kiri/src/store/modules/userSlice.js
- 마이페이지 개인정보 페이지 UI 구현
- 비밀번호 변경 페이지 구현
- 개인정보수정 api 연결
=> [FE] 마이페이지 기능 구현 및 api 연결

client/kiri/src/components/Header.js, client/kiri/src/containers/PageContainer.js, client/kiri/src/pages/Event/EventPage.js, client/kiri/src/pages/EventWrite/EventWritePage.js
- `PageContainer` 에다가 `page` 추가해서 작업
- 조건문을 잘못적어서 안뜨는 문제였던것 같다
=> 💄 [FE] style: header page 바로 뜨기

client/kiri/src/pages/EventWrite/EventExplainInput.js, client/kiri/src/pages/EventWrite/EventInfoInput.js, client/kiri/src/pages/EventWrite/EventTitleInput.js, client/kiri/src/pages/EventWrite/EventWritePage.js
- 미작성후 글쓰기 버튼을 누르면 경고 문구 뜨도록
- 작성하지 않은 영역에 focus 맞춤설정
- 작성한 영역은 글쓰기 버튼을 눌렀을때 문구 사라짐
필수 중 하나 작성 후 `글쓰기` 버튼을 눌렀을때
`주최/단체를 입력해주세요` 문구가 사라짐
=> [FE] 필수 내용 미작성시 경고 문구

client/kiri/src/api/setAuthHeader.js, client/kiri/src/pages/Mypage/MypageInputs.js, client/kiri/src/pages/PasswordChange/PasswordChangePage.js, client/kiri/src/pages/User/MyEvents.js, client/kiri/src/pages/User/UserPage.js
- setAuthHeader 함수 추가
- authorization 필요한 api 호출시 setAuthHeader 통해서 api 헤더 설정 필요
=> [FE] 인증 관련 작업

client/kiri/src/pages/Signin/SigninInputs.js
- 이메일, 비밀번호 입력후 엔터 누르면 로그인 가능하도록 기능 추가
=> [FE] 로그인시 엔터로 가능하도록 기능 추가

server/kiri/src/main/java/com/ssu/kiri/common/dto/MultipleResponseDto.java, server/kiri/src/main/java/com/ssu/kiri/post/Post.java, server/kiri/src/main/java/com/ssu/kiri/post/PostController.java, server/kiri/src/main/java/com/ssu/kiri/post/PostService.java, server/kiri/src/main/java/com/ssu/kiri/scrap/Scrap.java, server/kiri/src/main/java/com/ssu/kiri/scrap/ScrapController.java, server/kiri/src/main/java/com/ssu/kiri/scrap/ScrapCustomRepository.java, server/kiri/src/main/java/com/ssu/kiri/scrap/ScrapRepository.java, server/kiri/src/main/java/com/ssu/kiri/scrap/ScrapRepositoryImpl.java, server/kiri/src/main/java/com/ssu/kiri/scrap/ScrapService.java, server/kiri/src/main/java/com/ssu/kiri/scrap/dto/ScrapReqAdd.java, server/kiri/src/main/java/com/ssu/kiri/scrap/dto/ScrapResCal.java, server/kiri/src/test/java/com/ssu/kiri/post/PostControllerTest.java, server/kiri/src/test/java/com/ssu/kiri/post/PostServiceTest.java, server/kiri/src/test/java/com/ssu/kiri/scrap/ScrapControllerTest.java, server/kiri/src/test/java/com/ssu/kiri/scrap/ScrapServiceTest.java
- post 삭제 시 연관관계 삭제
- scrap 삭제(취소) 시 연관관계 삭제
- 스크랩(좋아요)한 게시글 정보 가져오기
=> [BE] 스크랩(좋아요)한 게시글 정보 가져오기

server/kiri/src/main/java/com/ssu/kiri/member/MemberController.java, server/kiri/src/main/java/com/ssu/kiri/member/MemberService.java, server/kiri/src/main/java/com/ssu/kiri/post/PostController.java, server/kiri/src/main/java/com/ssu/kiri/post/PostRepository.java, server/kiri/src/main/java/com/ssu/kiri/post/PostService.java, server/kiri/src/main/java/com/ssu/kiri/security/SecurityConfig.java, server/kiri/src/test/java/com/ssu/kiri/post/PostControllerTest.java, server/kiri/src/test/java/com/ssu/kiri/post/PostServiceTest.java
- 로그아웃 api 수정
- 게시글 검색 api 추가
- 내가 작성한 글 조회 api 추가
- 내가 작성한 글 조회 repository 따로 확인하기
=> 로그아웃, 개인 글 조회, 검색 api 추가

client/kiri/src/pages/User/MyEvents.js, client/kiri/src/pages/User/UserPage.js
- 내가 작성한 글 불러오는 api 연결
- 작성 글 없을시 안내문구 추가
=> [FE] 마이페이지 api 연결, UI 추가

server/kiri/src/main/java/com/ssu/kiri/post/PostController.java, server/kiri/src/main/java/com/ssu/kiri/post/PostService.java, server/kiri/src/main/java/com/ssu/kiri/post/dto/response/MyPostDto.java, server/kiri/src/test/java/com/ssu/kiri/post/PostServiceTest.java
- 내가 작성한 글 조회 api response dto 에 finishPostTime 값 추가
=> [BE] 내가 작성한 글 조회 api response dto 수정

client/kiri/package-lock.json, client/kiri/package.json, client/kiri/public/img/main_logo.svg, client/kiri/src/components/Header.js, client/kiri/src/components/calendar/Calendar.js, client/kiri/src/containers/PageContainer.js, client/kiri/src/pages/Calendar/Calendar.js, client/kiri/src/styles/theme.js
=> [FE] 캘린더 구현

client/kiri/src/pages/EventWrite/EventEtcInput.js, client/kiri/src/pages/EventWrite/EventInfoInput.js, client/kiri/src/pages/EventWrite/EventWritePage.js
=> [FE] 이미지 10개 제한

server/kiri/src/main/java/com/ssu/kiri/post/PostService.java
=> :bug: [BE] 게시글 등록 400 오류 해결

client/kiri/src/components/SearchUnivModal.js, client/kiri/src/pages/Event/EventContent.js, client/kiri/src/pages/Event/EventPage.js, client/kiri/src/pages/Event/EventRegion.js, client/kiri/src/pages/Event/EventTag.js, client/kiri/src/pages/EventWrite/EventInfoInput.js
- api 연결
- 눈 모양에서 하트로 변경
- Dday 계산 완료
- 데이터가 없어서 우선 더미데이터 사용!
=> ✨ [FE] feat: api 연결

client/kiri/src/pages/EventWrite/EventEtcInput.js, client/kiri/src/pages/EventWrite/EventWritePage.js
- 우선 test post 하는것만 성공
- img 업로드 남았음
=> [FE] feat: text post 성공

client/kiri/src/pages/Calendar/CalendarPage.js
=> ✨[FE] style: calendar header 바 구현

server/kiri/src/main/java/com/ssu/kiri/post/Post.java, server/kiri/src/main/java/com/ssu/kiri/post/PostController.java, server/kiri/src/main/java/com/ssu/kiri/post/PostCustomRepository.java, server/kiri/src/main/java/com/ssu/kiri/post/PostRepositoryImpl.java, server/kiri/src/main/java/com/ssu/kiri/post/PostService.java, server/kiri/src/main/java/com/ssu/kiri/post/dto/response/PostResCal.java, server/kiri/src/main/java/com/ssu/kiri/post/dto/response/SaveResPost.java, server/kiri/src/main/java/com/ssu/kiri/scrap/Scrap.java, server/kiri/src/main/java/com/ssu/kiri/scrap/ScrapController.java, server/kiri/src/main/java/com/ssu/kiri/scrap/ScrapRepositoryImpl.java, server/kiri/src/main/java/com/ssu/kiri/scrap/ScrapService.java, server/kiri/src/main/java/com/ssu/kiri/scrap/dto/ScrapResCal.java, server/kiri/src/main/java/com/ssu/kiri/security/SecurityConfig.java, server/kiri/src/main/resources/application.yml, server/kiri/src/test/java/com/ssu/kiri/post/PostControllerTest.java, server/kiri/src/test/java/com/ssu/kiri/post/PostServiceTest.java, server/kiri/src/test/java/com/ssu/kiri/scrap/ScrapControllerTest.java, server/kiri/src/test/java/com/ssu/kiri/scrap/ScrapServiceTest.java
- 로그아웃 상태에서 캘린더 접속시 기본 api 추가 (서울 지역 행사 보여주기)
- 게시글 등록 api email 누락 오류 해결
- 스크랩(좋아요) 등록, 취소 api 오류 수정
- 게시글 등록 api response 에 email 추가
- 게시글 수정 api 수정 예정
=> [BE] 캘린더, 게시글 api 추가 및 수정

client/kiri/src/pages/Mypage/MypageInput.js, client/kiri/src/pages/Signup/SignupInputs.js
- 회원가입시 학교 선택안함 가능
- 유저 개인정보 수정시 학교 선택안함 가능
=> [FE] 유저에 학교 선택안함 옵션 추가 

client/kiri/src/pages/Event/EventContent.js, client/kiri/src/pages/Event/EventInfoPage.js, client/kiri/src/pages/Event/EventPage.js, client/kiri/src/pages/Event/EventRegion.js, client/kiri/src/pages/Event/EventTag.js, client/kiri/src/store/modules/tagSlice.js, client/kiri/src/store/store.js
- 학교 + tag 여러가지 경우 연결
- 지역 + tag 여러가지 경우 연결
- redux 사용
=> 학교, 지역 - event tag 연결

server/kiri/src/main/java/com/ssu/kiri/post/Post.java, server/kiri/src/main/java/com/ssu/kiri/post/PostController.java, server/kiri/src/main/java/com/ssu/kiri/post/PostService.java, server/kiri/src/main/java/com/ssu/kiri/post/dto/response/ClassifyPost.java, server/kiri/src/main/java/com/ssu/kiri/scrap/ScrapController.java, server/kiri/src/main/java/com/ssu/kiri/scrap/ScrapCustomRepository.java, server/kiri/src/main/java/com/ssu/kiri/scrap/ScrapRepositoryImpl.java, server/kiri/src/main/java/com/ssu/kiri/scrap/ScrapService.java, server/kiri/src/main/java/com/ssu/kiri/security/SecurityConfig.java, server/kiri/src/main/resources/application.yml, server/kiri/src/test/java/com/ssu/kiri/post/PostControllerTest.java, server/kiri/src/test/java/com/ssu/kiri/post/PostServiceTest.java, server/kiri/src/test/java/com/ssu/kiri/scrap/ScrapControllerTest.java, server/kiri/src/test/java/com/ssu/kiri/scrap/ScrapServiceTest.java
- 게시글 수정 api 수정
- 캘린더 기본화면(로그아웃 시) api 분리
- 카테고리별 조회 response dto 수정
=> :bug: [BE] 게시글 api 수정

client/kiri/src/pages/Event/EventContent.js, client/kiri/src/pages/EventWrite/EventWritePage.js
=> 🐛 [FE] fix: event page data 에러 수정

client/kiri/src/pages/Signin/SigninInputs.js, client/kiri/src/store/modules/userSlice.js
=> :sparkles: [FE] fix: 로그인시 memberId redux에 저장

client/kiri/src/components/PostModal.js, client/kiri/src/pages/EventWrite/EventWritePage.js
=>  ✨ [FE] feat: 게시물 등록 alert

server/kiri/src/main/java/com/ssu/kiri/post/PostController.java, server/kiri/src/main/java/com/ssu/kiri/post/PostService.java, server/kiri/src/main/java/com/ssu/kiri/post/dto/response/DetailPost.java, server/kiri/src/test/java/com/ssu/kiri/post/PostControllerTest.java, server/kiri/src/test/java/com/ssu/kiri/post/PostServiceTest.java
=> [BE] Post 기능 수정

client/kiri/src/components/PostModal.js, client/kiri/src/components/PostRemoveModal.js, client/kiri/src/pages/Event/EventInfoPage.js, client/kiri/src/pages/EventEdit/EventEditPage.js, client/kiri/src/pages/EventWrite/EventWritePage.js
- 게시글 등록 alert 디자인
- 게시글 수정 alert 디자인 완료
=> [FE] style: 게시글 등록, 수정 모달 디자인

client/kiri/src/pages/Event/EventPage.js, client/kiri/src/pages/Event/EventRegion.js
=> 🐛 [FE] fix: pagination error 수정

client/kiri/src/pages/Event/EventContent.js, client/kiri/src/pages/Event/EventInfoPage.js
event type `tag` 이벤트 전체 페이지, 상세페이지에 추가
디자인이 과연 괜찮은지...
- 타입별 색상 입히기
=> ✨ [FE] feat: tag 정보 추가

client/kiri/src/components/calendar/AllEventModal.js, client/kiri/src/components/calendar/AllLikedEvent.js, client/kiri/src/components/calendar/Calendar.js, client/kiri/src/components/calendar/EventModal.js, client/kiri/src/pages/Calendar/CalendarPage.js, client/kiri/src/pages/EventWrite/EventWritePage.js
- 한 날짜에 여러 이벤트 포함시 모달 처리
- 좋아요한 이벤트 / 지역별 이벤트 조회 가능
- 우선 UI는 모두 구현 (캘린더 파일 오류는 추후 수정 필요)
=> [FE] 캘린더 추가 기능 구현

client/kiri/src/components/calendar/EventModal.js
=> [FE] 캘린더 관련 버그 수정

client/kiri/src/components/Footer.js, client/kiri/src/components/Header.js, client/kiri/src/containers/PageContainer.js, client/kiri/src/pages/Main/MainPage.js, client/kiri/src/pages/Signin/SigninInputs.js, client/kiri/src/pages/Signup/SignupInputs.js, client/kiri/src/pages/User/MyEvents.js, client/kiri/src/styles/Globalstyle.js
- 레이아웃 깨지는 현상 수정
- 헤더 레이아웃 수정
- 푸터 수정
=> [FE] 페이지 레이아웃, 헤더, 푸터 수정

client/kiri/src/pages/Event/EventContent.js, client/kiri/src/pages/Event/EventInfoPage.js, client/kiri/src/pages/Event/EventTag.js
tag에 색깔 입히기 완료
- margin: auto 로 해서 중앙정렬 맞췄는데 뭔가 살짝 올라가보임..
=> tag 색깔 입히기

client/kiri/src/pages/EventWrite/EventEtcInput.js, client/kiri/src/pages/EventWrite/EventWritePage.js
=> ✨ [FE] feat: img 필수로 변경

client/kiri/package-lock.json, client/kiri/package.json, client/kiri/src/components/Footer.js, client/kiri/src/components/Header.js, client/kiri/src/components/MobileHeader.js, client/kiri/src/components/calendar/Calendar.js, client/kiri/src/containers/PageContainer.js, client/kiri/src/pages/Calendar/CalendarPage.js, client/kiri/src/styles/Globalstyle.js
- 페이지 레이아웃 모바일 사이즈에 맞게 적용
- 캘린더 사이즈 조절
- 모바일 헤더 구현
- MUI 설치로 npm i 필요!!
=> [FE] 모바일 UI - 페이지 레이아웃, 캘린더, 헤더 등

client/kiri/src/pages/Signin/SigninInputs.js, client/kiri/src/pages/Signup/SignupInputs.js
- 회원가입, 로그인 페이지 모바일 반응형 레이아웃 적용
=> [FE] 회원가입, 로그인 페이지 모바일 반응형 레이아웃 적용

client/kiri/src/pages/Mypage/Mypage.js, client/kiri/src/pages/Mypage/MypageInput.js, client/kiri/src/pages/Mypage/MypageInputs.js, client/kiri/src/pages/Mypage/Withdraw.js, client/kiri/src/pages/PasswordChange/PasswordChangePage.js, client/kiri/src/pages/User/MyEvents.js, client/kiri/src/pages/User/UserInfo.js
- 마이페이지, 개인정보수정 페이지, 비밀번호 변경 페이지 모바일 UI 적용
=> [FE] 마이페이지, 개인정보 수정 페이지 모바일 반응형 UI 적용

client/kiri/src/pages/Event/EventContent.js, client/kiri/src/pages/EventEdit/EventEditPage.js
- merge 후 eslint 에러 수정
- edit 임시방편으로 수정
=> 🐛 [FE] fix: edit error 오류 해결

server/kiri/src/main/java/com/ssu/kiri/post/PostController.java, server/kiri/src/main/java/com/ssu/kiri/post/PostService.java, server/kiri/src/main/java/com/ssu/kiri/post/dto/response/DetailPost.java, server/kiri/src/main/java/com/ssu/kiri/post/dto/response/MyPostDto.java
- 게시글 상세보기 시, response dto 중 사용자의 scrap 여부 변수명 확인
- 게시글 상세보기 시, response dto 에 [이미지 id List] 추가
- 내가 쓴 글 조회시 response dto에 [event 타입] 추가
- 게시글 상세보기 시 response dto 중 '사용자의 scrap 여부' 변수명 isScrap인지 확인 및 수정 필요
=> [BE] 게시글 상세보기 수정

client/kiri/src/pages/Event/EventPage.js, client/kiri/src/pages/Event/EventRegion.js, client/kiri/src/pages/Event/EventTag.js
=> [FE] eventTag 모바일 사이즈 맞춤

client/kiri/src/pages/Event/EventInfoPage.js
=> 🐛 [FE] fix: scrap 여부 수정

client/kiri/src/pages/Event/EventInfoPage.js
=> 🐛 [FE] fix: input enter 인식

client/kiri/src/pages/EventEdit/EventEditPage.js, client/kiri/src/pages/EventEdit/EventEtcInput.js, client/kiri/src/pages/EventWrite/EventEtcInput.js, client/kiri/src/pages/EventWrite/EventWritePage.js
- 이벤트 수정시 그림 0개면 이미지 첨부 문구 뜨도록
- 이벤트 최초로 업로드시에도 설정이 안되어있어서 같이 수정!
=> 🐛 [FE] fix: 이벤트 그림 필수로 수정

server/kiri/src/main/java/com/ssu/kiri/post/dto/request/SavePost.java
- 게시글 작성 시 request dto 의 email 입력 필수 -> 선택 으로 변경
=> :adhesive_bandage: [BE] 게시글 작성 시 request dto 수정

client/kiri/src/components/calendar/EventModal.js, client/kiri/src/pages/Calendar/CreateIcsFile.js
- 끝나는 날짜가 하루 앞당겨져서 저장되는 버그 수정
- 이제 캘린더 파일 내보내기 잘됨!
=> [FE] 캘린더 이벤트 내보내기 날짜 버그 수정

client/kiri/src/pages/EventEdit/EventEtcInput.js, client/kiri/src/pages/EventWrite/EventEtcInput.js
=> 💄 [FE] style: 게시글 수정시 이미지 * 표시 추가

server/kiri/src/main/java/com/ssu/kiri/image/ImageController.java, server/kiri/src/main/java/com/ssu/kiri/image/ImageService.java, server/kiri/src/main/java/com/ssu/kiri/post/Post.java, server/kiri/src/main/java/com/ssu/kiri/post/PostController.java, server/kiri/src/main/java/com/ssu/kiri/post/PostService.java, server/kiri/src/main/java/com/ssu/kiri/post/dto/response/SaveResPost.java, server/kiri/src/main/java/com/ssu/kiri/scrap/Scrap.java, server/kiri/src/main/java/com/ssu/kiri/scrap/ScrapService.java, server/kiri/src/main/java/com/ssu/kiri/security/auth/PrincipalDetailsService.java, server/kiri/src/main/java/com/ssu/kiri/security/jwt/JwtAuthenticationFilter.java, server/kiri/src/main/java/com/ssu/kiri/security/jwt/JwtAuthorizationFilter.java, server/kiri/src/main/java/com/ssu/kiri/security/jwt/JwtTokenProvider.java, server/kiri/src/main/resources/application.yml
=> yml 파일 수정 및 불필요한 코드 주석 처리

client/kiri/.eslintrc.json, client/kiri/src/components/calendar/AllLikedEvent.js, client/kiri/src/components/calendar/Calendar.js, client/kiri/src/components/calendar/LikedEvent.js, client/kiri/src/pages/Calendar/CalendarPage.js
- 모바일 캘린더 UI 수정: 해당 날짜에 이벤트 몇개 있는지
- 캘린더 하단 이벤트 목록 UI는 구현 예정
=> [FE] 모바일 캘린더 작업

client/kiri/package.json, client/kiri/src/pages/Event/EventInfoPage.js
=> ✨ [FE] feat: info 추가

client/kiri/src/components/Header.js, client/kiri/src/pages/Event/EventPage.js, client/kiri/src/pages/Event/EventTag.js, client/kiri/src/pages/Mypage/Withdraw.js, client/kiri/src/pages/Signup/SignupInputs.js
=> [FE] 자잘한 디자인 수정

client/kiri/src/pages/Event/EventInfoPage.js, client/kiri/src/pages/Event/EventPage.js
=> 🐛 [FE] fix: console창 에러 수정

client/kiri/.eslintrc.json, client/kiri/src/components/Pagination.js, client/kiri/src/pages/Event/EventContent.js, client/kiri/src/pages/Event/EventInfoPage.js, client/kiri/src/pages/Event/EventPage.js
- console.log 삭제
- 버그 fix
- 아이콘 통일
=> [FE] 중간전시 전 에러 수정 

client/kiri/src/components/calendar/Calendar.js, client/kiri/src/pages/Event/EventInfoPage.js
=> [FE] eslint 에러 수정

client/kiri/src/pages/Event/EventTag.js
=> 🔥 [FE] style: delete console

client/kiri/src/pages/Main/MainPage.js
=> [FE] 메인페이지에 이미지 추가

client/kiri/src/pages/Event/EventInfoPage.js, client/kiri/src/pages/EventEdit/EventInfoInput.js, client/kiri/src/pages/EventEdit/EventTitleInput.js
- map에 key item 수정
- 옵셔널 체이닝 추가
=> [FE] 버그 수정 

client/kiri/public/manifest.json, client/kiri/src/pages/Event/EventInfoPage.js
=> 🐛 [FE] fix: console error

client/kiri/src/pages/EventEdit/EventEditPage.js, client/kiri/src/pages/EventEdit/EventEtcInput.js, client/kiri/src/pages/EventEdit/EventExplainInput.js, client/kiri/src/pages/EventEdit/EventInfoInput.js, client/kiri/src/pages/EventEdit/EventTitleInput.js, client/kiri/src/pages/EventWrite/EventEtcInput.js, client/kiri/src/pages/EventWrite/EventExplainInput.js, client/kiri/src/pages/EventWrite/EventInfoInput.js, client/kiri/src/pages/EventWrite/EventTitleInput.js, client/kiri/src/pages/EventWrite/EventWritePage.js
=> 💄 [FE] style: 모바일 수정 완료

server/kiri/src/main/java/com/ssu/kiri/config/WebMvcConfig.java, server/kiri/src/main/java/com/ssu/kiri/image/Image.java, server/kiri/src/main/java/com/ssu/kiri/post/Post.java
- post의 content 길이 제한 수정
- cors 설정 수정
=> cors 및 기타 수정

server/kiri/src/main/resources/application.yml
- yml 파일 수정
- cloud.aws.credentials.instanceProfile: true 주석 해제
=> :wrench: [BE] yml 파일 수정

client/kiri/src/components/calendar/Calendar.js, client/kiri/src/components/calendar/MobileLikedEventList.js, client/kiri/src/components/calendar/MobileLikedEvents.js, client/kiri/src/components/calendar/SavedDate.js, client/kiri/src/pages/Calendar/CalendarPage.js
- 웹 버전, 모바일 버전 캘린더 UI 수정
- 모바일 버전에서 캘린더로 좋아요한 이벤트 목록 확인 가능
=> [FE] 캘린더 UI 수정

server/kiri/build.gradle
=> :bug: [BE] build.gradle 파일 수정

client/kiri/src/components/ImgBox.js, client/kiri/src/pages/EventWrite/EventEtcInput.js, client/kiri/src/pages/EventWrite/EventExplainInput.js, client/kiri/src/store/modules/ocrSlice.js, client/kiri/src/store/store.js
- google vision API 연결 완료
- img 부분 `imgBox.js` 컴포넌트 따로 생성
- ocr 결과물 redux로 관리
- 우선 결과 여부 확인하기 위해 설명 안에 넣었음!!
- OCR 하기 버튼 디자인 논의 필요...🥲
- OCR 인식하려면 `.env` 파일에 `REACT_APP_API_KEY` 변수명으로 google vision API KEY 넣어야됨!!
=> ✨ [FE] feat: google API 연결 완료

client/kiri/src/components/ImgBox.js, client/kiri/src/pages/EventWrite/EventEtcInput.js, client/kiri/src/pages/EventWrite/EventExplainInput.js, client/kiri/src/pages/EventWrite/EventInfoInput.js, client/kiri/src/pages/EventWrite/EventTitleInput.js, client/kiri/src/pages/EventWrite/EventWritePage.js
=> ✨ [FE] feat: openai 연결 완료

server/kiri/build.gradle, server/kiri/src/main/java/com/ssu/kiri/image/Image.java, server/kiri/src/main/java/com/ssu/kiri/post/Post.java
- build.gradle 수정
- post의 content, image의 imgUrl 길이제한 수정
=> [BE] build.gradle 수정

client/kiri/src/components/ImgBox.js, client/kiri/src/pages/EventWrite/EventInfoInput.js, client/kiri/src/pages/EventWrite/EventTagInput.js
=> ✨ [FE] feat: api tag 연결

client/kiri/src/components/buttons/SearchUnivBtn.js, client/kiri/src/pages/Event/EventContent.js, client/kiri/src/pages/Event/EventInfoPage.js, client/kiri/src/pages/Event/EventPage.js, client/kiri/src/pages/Event/EventRegion.js, client/kiri/src/pages/Event/EventSearchPage.js, client/kiri/src/pages/EventWrite/EventEtcInput.js, client/kiri/src/pages/EventWrite/EventExplainInput.js, client/kiri/src/pages/EventWrite/EventInfoInput.js, client/kiri/src/pages/EventWrite/EventTagInput.js, client/kiri/src/pages/EventWrite/EventTitleInput.js
=> [FE] style: 모바일 버전 UI 수정

client/kiri/src/components/ImgBox.js
=> [FE] prettier 에러 수정해서 재배포

client/kiri/src/pages/EventEdit/EventEditPage.js
=> [FE] 이벤트 수정 페이지에 태그 UI 추가

client/kiri/src/components/ImgBox.js, client/kiri/src/pages/EventWrite/EventEtcInput.js, client/kiri/src/pages/EventWrite/EventTagInput.js
=> 💄 [FE] style: 태그, 참고링크, 이미지 간 간격 조절

client/kiri/src/components/Footer.js
=> [FE] Release 2.0.0

client/kiri/src/pages/Event/EventInfoPage.js, client/kiri/src/pages/Event/Recommends.js
- 이벤트 상세 조회 페이지 추천 게시물 UI 추가
- 웹 버전 / 모바일 버전 UI 다름
- 클릭시 해당 게시물로 이동
- api 에 이미지 url 추가되면 수정 필요!
=> [FE] feat: 추천 게시물 UI

client/kiri/src/pages/Event/EventPage.js, client/kiri/src/pages/Event/EventRegion.js
=> 💄 [FE] style: 게시물 필터 삭제

client/kiri/src/components/ImgBox.js, client/kiri/src/pages/EventWrite/EventImg.js, client/kiri/src/pages/EventWrite/EventInfoInput.js
=> 💄 [FE] style: mobile 게시물 이미지 미리보기 UI 수정

client/kiri/src/pages/Event/Recommends.js
=> fix: 추천 게시물 이미지 링크 연결

client/kiri/src/components/ImgBox.js
`제목, 이메일, 주최, 장소, 대학교, 시작날짜, 끝나는날짜, 연락처, 시작시간, 끝나는시간, 핵심키워드5개` 에서 `대학교` 삭제
=> ✨ [FE] feat: 질문 문구 수정

client/kiri/src/components/ImgBox.js, client/kiri/src/pages/EventWrite/EventInfoInput.js
=> 🚨 [FE] fix: post error

client/kiri/src/pages/EventWrite/EventInfoInput.js
=> 🚨 [FE] fix: base 초기화값으로 수정

client/kiri/src/pages/EventEdit/EventEditPage.js
=> fix: 옵셔널 체이닝 추가

client/kiri/src/pages/Event/EventInfoPage.js
=> 🚨 [FE] fix: scrap 반영

client/kiri/src/pages/Event/EventInfoPage.js
=> ✨ [FE] feat: tag info 추가

client/kiri/src/pages/Event/Recommends.js, client/kiri/src/pages/EventEdit/EventEditPage.js
- api 변경으로 에러나던거 픽스
- 이벤트 상세 조회에서 추천 게시물 없어도 UI는 보이도록함
=> [FE] fix: 이벤트 수정 페이지 에러 픽스

client/kiri/src/components/ImgBox.js, client/kiri/src/pages/Event/EventInfoPage.js, client/kiri/src/pages/EventEdit/EventEditPage.js, client/kiri/src/pages/EventEdit/EventEditTagInput.js, client/kiri/src/pages/EventWrite/EventTagInput.js, client/kiri/src/pages/EventWrite/EventWritePage.js
- 이벤트 게시글 수정에서 태그 반영안되던 것들 수정
- 오픈 ai request 문구 수정 (태그, 장소 한글로)
=> [FE] fix: 태그 관련 수정사항 반영

client/kiri/src/components/Footer.js, client/kiri/src/components/ImgBox.js, client/kiri/src/pages/Event/EventInfoPage.js, client/kiri/src/pages/Event/EventSearchPage.js, client/kiri/src/pages/Event/Recommends.js, client/kiri/src/pages/EventEdit/EventEditPage.js, client/kiri/src/pages/EventEdit/EventEditTagInput.js, client/kiri/src/pages/EventWrite/EventWritePage.js
=> Release 2.1.2

client/kiri/src/components/Header.js, client/kiri/src/pages/Event/EventInfoPage.js, client/kiri/src/pages/Event/EventPage.js, client/kiri/src/pages/Event/Recommends.js, client/kiri/src/pages/EventWrite/EventInfoInput.js
=> [FE] fix: QA 사항 반영

client/kiri/src/pages/EventWrite/EventTagInput.js
- 모바일 환경에서 엔터키가 없는 경우를 위해 스페이스바를 눌렀을때에도 태그가 추가되도록 변경
=> ✨ [FE] fix: tag 추가시 spacebar 눌러도 추가

client/kiri/src/components/Footer.js
=> hotfix: 메인 이미지 포맷 변경

client/kiri/src/pages/Event/EventContent.js, client/kiri/src/pages/Event/EventPage.js, client/kiri/src/pages/Event/EventRegion.js
=> 💄 [FE] style: img list marign 변경

client/kiri/src/components/Footer.js, client/kiri/src/pages/Event/EventContent.js, client/kiri/src/pages/Event/EventPage.js, client/kiri/src/pages/Event/EventRegion.js
=> Release 2.1.6

client/kiri/src/pages/Event/EventContent.js
=> event list 여백 적용

client/kiri/src/components/Footer.js, client/kiri/src/pages/EventWrite/EventImg.js
=> Relase 2.1.7

client/kiri/src/components/ImageErrorModal.js, client/kiri/src/pages/EventWrite/EventImg.js
useEffect 사용 -> 업로드 후 preview 뜨는데까지 시간 좀 걸림
큰이미지 올리면 경고 모달창
=> big image 업로드 시 생기는 오류 해결

client/kiri/src/pages/EventWrite/EventTagInput.js
받아오는 data 명을 keywords 에서 keyword로 수정
=> 🐛 [FE] fix: Tag input 받아오는 명 변경

client/kiri/src/pages/Event/EventInfoPage.js
=> 💄 [FE] style: 긴 글자 깨짐 수정

client/kiri/src/pages/Event/EventInfoPage.js
=> 💄 [FE] style: 이메일 깨짐 수정

client/kiri/src/pages/Event/EventInfoPage.js
=> 💄 [FE] style: whitespace 적용

client/kiri/src/pages/Event/EventInfoPage.js, client/kiri/src/pages/EventWrite/EventTagInput.js
=> Release 2.1.9

client/kiri/src/pages/EventWrite/EventTagInput.js
=> 🐛 [FE] fix: openAI tag

client/kiri/src/pages/Event/EventInfoPage.js, client/kiri/src/pages/EventWrite/EventTagInput.js
=> Release 2.1.10

client/kiri/src/pages/EventWrite/EventImg.js, client/kiri/src/pages/EventWrite/EventTagInput.js
=> 🔥 [FE] style: console 삭제
